CREATE USER master WITH PASSWORD 'HgAXVS5uWph3' SUPERUSER;

CREATE USER query_user WITH PASSWORD 'J5jY6vUttdF7';
GRANT USAGE ON SCHEMA public TO query_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO query_user;

